apiVersion: v1
kind: Namespace
metadata:
  name: fintech-production
  labels:
    name: fintech-production
    environment: production
    team: fintech
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
    team: platform 