groups:
  - name: fintech-platform-alerts
    rules:
      # High-level system alerts
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }} seconds"

      # Document processing alerts
      - alert: DocumentProcessingQueueBacklog
        expr: kafka_consumer_lag_sum{topic="document-processing"} > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Document processing queue backlog"
          description: "Queue has {{ $value }} pending documents"

      - alert: MLModelInferenceFailure
        expr: rate(ml_inference_failures_total[5m]) > 0.05
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "ML model inference failures"
          description: "ML model failure rate is {{ $value }} per second"

      # Infrastructure alerts
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting"

      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="true"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Kubernetes node not ready"
          description: "Node {{ $labels.node }} is not ready"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database connections high"
          description: "Database connections are at {{ $value | humanizePercentage }}"

      # Business metrics alerts
      - alert: DocumentProcessingSlow
        expr: rate(documents_processed_total[5m]) < 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Document processing rate is slow"
          description: "Processing rate is {{ $value }} documents per second"

      - alert: APIResponseTimeDegraded
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API response time degraded"
          description: "99th percentile response time is {{ $value }} seconds"

      # Service-specific alerts
      - alert: APIGatewayDown
        expr: up{job="api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API Gateway is down"
          description: "API Gateway service is not responding"

      - alert: MLServiceDown
        expr: up{job="ml-service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "ML Service is down"
          description: "ML processing service is not responding"

      - alert: GoServiceDown
        expr: up{job="go-orchestrator"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Go Orchestrator is down"
          description: "Service orchestration is not responding"

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "Database service is not responding"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis is down"
          description: "Cache service is not responding"

      # Resource utilization alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value | humanizePercentage }}"

      # Network alerts
      - alert: HighNetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network errors"
          description: "Network error rate is {{ $value }} errors per second" 