apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
  namespace: fintech-platform
  labels:
    app: go-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
        version: v1
    spec:
      containers:
      - name: go-service
        image: fintech-ai-platform/go-service:latest
        ports:
        - containerPort: 8003
          name: http
        - containerPort: 9093
          name: metrics
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: go-service-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: go-service-secrets
              key: redis-url
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: go-service-secrets
              key: jwt-secret
        - name: DEBUG
          value: "false"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8003"
        - name: PROMETHEUS_PORT
          value: "9093"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: fintech-platform
  labels:
    app: go-service
spec:
  selector:
    app: go-service
  ports:
  - name: http
    port: 8003
    targetPort: 8003
  - name: metrics
    port: 9093
    targetPort: 9093
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: go-service-secrets
  namespace: fintech-platform
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2dvX3VzZXI6Z29fcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9maW50ZWNoX29yY2hlc3RyYXRvcg==
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5LzI=
  jwt-secret: <base64-encoded-jwt-secret> 