apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
  namespace: fintech-platform
  labels:
    app: java-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
        version: v1
    spec:
      containers:
      - name: java-service
        image: fintech-ai-platform/java-service:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9094
          name: metrics
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: java-service-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: java-service-secrets
              key: jwt-secret
        - name: SERVER_PORT
          value: "8080"
        - name: MANAGEMENT_SERVER_PORT
          value: "9094"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: fintech-platform
  labels:
    app: java-service
spec:
  selector:
    app: java-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9094
    targetPort: 9094
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: java-service-secrets
  namespace: fintech-platform
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL2phdmFfdXNlcjpqYXZhX3Bhc3N3b3JkQHBvc3RncmVzOjU0MzIvZmludGVjaF9rYWZrYQ==
  jwt-secret: <base64-encoded-jwt-secret> 